In [1]:
import collections

In [2]:
# Parameters for the entire model (stem, all blocks, and head)
GlobalParams = collections.namedtuple('GlobalParams', [
    'batch_norm_momentum', 'batch_norm_epsilon', 'dropout_rate',
    'num_classes', 'width_coefficient', 'depth_coefficient',
    'depth_divisor', 'min_depth', 'drop_connect_rate', 'image_size'])

In [3]:
w, d, s, p = (1.6, 2.2, 456, 0.4)

In [4]:
width_coefficient=None
depth_coefficient=None
dropout_rate=0.2
drop_connect_rate=0.2
image_size=None
num_classes=1000

In [5]:
width_coefficient=w
depth_coefficient=d
dropout_rate=p
image_size=s

In [6]:
global_params = GlobalParams(
    batch_norm_momentum=0.99,
    batch_norm_epsilon=1e-3,
    dropout_rate=dropout_rate,
    drop_connect_rate=drop_connect_rate,
    # data_format='channels_last',  # removed, this is always true in PyTorch
    num_classes=num_classes,
    width_coefficient=width_coefficient,
    depth_coefficient=depth_coefficient,
    depth_divisor=8,
    min_depth=None,
    image_size=image_size,
)

In [7]:
global_params

GlobalParams(batch_norm_momentum=0.99, batch_norm_epsilon=0.001, dropout_rate=0.4, num_classes=1000, width_coefficient=1.6, depth_coefficient=2.2, depth_divisor=8, min_depth=None, drop_connect_rate=0.2, image_size=456)

In [8]:
multiplier = global_params.width_coefficient
multiplier

1.6

In [9]:
divisor = global_params.depth_divisor
divisor

8

In [10]:
min_depth = global_params.min_depth
min_depth

In [11]:
16.2//8

2.0

In [12]:
import math

In [13]:
int(11.6)

11

In [14]:
for i in range(29):
    print(i, int(i + divisor / 2) // divisor, i//divisor+1/2)

0 0 0.5
1 0 0.5
2 0 0.5
3 0 0.5
4 1 0.5
5 1 0.5
6 1 0.5
7 1 0.5
8 1 1.5
9 1 1.5
10 1 1.5
11 1 1.5
12 2 1.5
13 2 1.5
14 2 1.5
15 2 1.5
16 2 2.5
17 2 2.5
18 2 2.5
19 2 2.5
20 3 2.5
21 3 2.5
22 3 2.5
23 3 2.5
24 3 3.5
25 3 3.5
26 3 3.5
27 3 3.5
28 4 3.5


In [15]:
divisor = 8
print("original", "enlarged", "raw_enlarged")
for filters in range(0,65):
    reserve_filters = filters
    filters *= multiplier
    min_depth = min_depth or divisor
    print(reserve_filters,'\t', max(min_depth, int(filters + divisor / 2) // divisor * divisor), "\t  {:.1f}".format(filters))
#     print((int(filters + divisor / 2) // divisor * divisor)/filters)

original enlarged raw_enlarged
0 	 8 	  0.0
1 	 8 	  1.6
2 	 8 	  3.2
3 	 8 	  4.8
4 	 8 	  6.4
5 	 8 	  8.0
6 	 8 	  9.6
7 	 8 	  11.2
8 	 16 	  12.8
9 	 16 	  14.4
10 	 16 	  16.0
11 	 16 	  17.6
12 	 16 	  19.2
13 	 24 	  20.8
14 	 24 	  22.4
15 	 24 	  24.0
16 	 24 	  25.6
17 	 24 	  27.2
18 	 32 	  28.8
19 	 32 	  30.4
20 	 32 	  32.0
21 	 32 	  33.6
22 	 32 	  35.2
23 	 40 	  36.8
24 	 40 	  38.4
25 	 40 	  40.0
26 	 40 	  41.6
27 	 40 	  43.2
28 	 48 	  44.8
29 	 48 	  46.4
30 	 48 	  48.0
31 	 48 	  49.6
32 	 48 	  51.2
33 	 56 	  52.8
34 	 56 	  54.4
35 	 56 	  56.0
36 	 56 	  57.6
37 	 56 	  59.2
38 	 64 	  60.8
39 	 64 	  62.4
40 	 64 	  64.0
41 	 64 	  65.6
42 	 64 	  67.2
43 	 72 	  68.8
44 	 72 	  70.4
45 	 72 	  72.0
46 	 72 	  73.6
47 	 72 	  75.2
48 	 80 	  76.8
49 	 80 	  78.4
50 	 80 	  80.0
51 	 80 	  81.6
52 	 80 	  83.2
53 	 88 	  84.8
54 	 88 	  86.4
55 	 88 	  88.0
56 	 88 	  89.6
57 	 88 	  91.2
58 	 96 	  92.8
59 	 96 	  94.4
60 	 96 	  96.0
61 	 96 	  97.6
62

In [16]:
filters *= multiplier
filters

163.84000000000003

In [17]:
min_depth = min_depth or divisor
min_depth

8

In [18]:
int(filters + divisor / 2) // divisor * divisor

160

In [19]:
0.9 * filters

147.45600000000005

In [20]:
import torch

In [21]:
random_tensor = 0.7
random_tensor += torch.rand([32, 1, 1, 1])

In [22]:
random_tensor.size()

torch.Size([32, 1, 1, 1])

In [23]:
random_tensor

tensor([[[[1.3432]]],


        [[[1.0057]]],


        [[[1.3466]]],


        [[[0.7762]]],


        [[[1.5343]]],


        [[[1.3978]]],


        [[[1.4116]]],


        [[[0.8144]]],


        [[[1.1580]]],


        [[[1.6051]]],


        [[[0.9519]]],


        [[[0.8676]]],


        [[[1.6145]]],


        [[[1.4410]]],


        [[[0.7030]]],


        [[[1.0080]]],


        [[[1.3719]]],


        [[[0.7435]]],


        [[[1.5560]]],


        [[[1.6014]]],


        [[[1.6060]]],


        [[[1.2913]]],


        [[[1.2301]]],


        [[[1.2452]]],


        [[[1.5272]]],


        [[[1.3938]]],


        [[[0.7095]]],


        [[[1.4193]]],


        [[[1.4672]]],


        [[[1.2569]]],


        [[[1.6211]]],


        [[[1.0012]]]])

In [42]:
(((torch.ones([32,3,224,224]) /0.7)*torch.floor(random_tensor))[3])

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [38]:
torch.floor(random_tensor)

tensor([[[[1.]]],


        [[[1.]]],


        [[[0.]]],


        [[[0.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[0.]]],


        [[[1.]]],


        [[[0.]]],


        [[[1.]]],


        [[[1.]]],


        [[[0.]]],


        [[[0.]]],


        [[[0.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[0.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[1.]]],


        [[[0.]]],


        [[[0.]]]])